name: Deploy to DEV
on: 
  push: 
    branches:
      - main
jobs:
  build:
    name: Generate Build and Deploy to DEV
   # environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
    
      - name: Copy .env file
        env:
          ENV_FILE_CONTENT: ${{ secrets.env }}
        run: echo "$ENV_FILE_CONTENT" > .env

          
      - name: Generate React Build
        run: |
         npm install
         npm run build


      - name: Show PWD
        run: |
           echo "Current Working Directory:"
           pwd
           
      - name: Create Directory
        run: mkdir my_directory

      - name: List Contents
        run: |
           echo "Contents of the current directory (in reverse order):"
            ls -lr

      - name: List Contents
        run: |
           echo "Contents of the dist directory (in reverse order):"
            cd /home/runner/work/sky-analytics/sky-analytics/dist
            ls -lr

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Set up SSH key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         # Add the SSH key to the known_hosts file (replace hostname with your actual hostname)
         ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts


      - name: Deploy with rsync
        run: |
           rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./dist/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/sky-analytics-bap.becknprotocol.io.conf/public


   
